//constructores:es una funcion que sirve para contruir o inicializar
//objetos. es una funcion que sirve para construir un nuevo objeto
//y asignar valores a sus mienbros se caracteriza por:
//1. tener el mismo nombre que la clase que incializa
//2. puede def inline
//3. no devuelve valores
//4. puede admitir parametros como cualquir otra funcion
//5.puede existir mas de un constructor
#include <iostream.h>
#include <conio.h>
class circulo{
private:
int x_cen,y_cen;
double rad;
public:
circulo(int x, int y, ddouble r) //funcion constructora
{
rad =r
x_cen=




