
#include"iostream.h"
#include"conio.h"
int readl(int a);
long readl(long a);
float readl(float a);
double readl(double a);
char readl(char a);
char readl( char a){
 cin>>a;
 return a;
 }
int readl( int a){
 cin>>a;
 return a;
 }
long readl( long a){
 cin>>a;
 return a;
 }
float readl( float a){
 cin>>a;
 return a;
 }
 double readl( double a){
 cin>>a;
 return a;
 }
void main(){
int a=readl(a);
long b=readl(b);
float c=readl(c);
double d=readl(d);
char e=readl(e);
getch();
}

