# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3wGUwH-RGaP5hJ2i6PFwqXqflUw-GBI
"""

!pip install qrcode
!pip install python-barcode

import qrcode
import barcode
import matplotlib.pyplot as plt


qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=0,
)

vcard = """BEGIN:VCARD
VERSION:4.0
N:Doe;John;;;
FN:John Doe
ORG:Example Inc.
TITLE:Manager
TEL;TYPE=WORK,VOICE:+569-0000-0000
EMAIL:example@example.com
URL:https://www.example.com
ADR;TYPE=WORK:;;123 Main St;Anytown;CA;12345;USA
END:VCARD"""


data = "https://www.example.com"

datas = [data, vcard]
for i in datas:
  qr.add_data(i)
  qr.make(fit=True)


  img = qr.make_image(fill_color="black", back_color="transparent")

  plt.axis('off')
  plt.grid(False)
  plt.imshow(img)
  plt.show()


data = "ABCDEFGH"
code = barcode.Code128(data, writer=barcode.writer.ImageWriter())

img = code.render()

plt.imshow(img)
plt.axis('off')
plt.grid(False)
plt.show()