# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_36Wl6zYYQRRkdQObzs5juumQsVQQP1n
"""

import random

def estimar_pi(num_puntos):
    puntos_dentro_circulo = 0

    for _ in range(num_puntos):
        x = random.uniform(0, 1)
        y = random.uniform(0, 1)
        distancia_al_centro = x**2 + y**2

        if distancia_al_centro <= 1:
            puntos_dentro_circulo += 1

    pi_estimado = 4 * (puntos_dentro_circulo / num_puntos)
    return pi_estimado

# Número de puntos a generar
num_puntos = 1000000

pi_aproximado = estimar_pi(num_puntos)
print(f"Estimación de Pi con {num_puntos} puntos: {pi_aproximado}")